version: "3.8"

services:
  apache:
    image: httpd
    container_name: apache-app
    ports:
      - "80:80"
    volumes:
      - ./website:/usr/local/apache2/htdocs
    networks:
      - minha-rede
networks:
  minha-rede:
    driver: bridge
